# Generated by Django 6.0.6 on 2026-07-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0018_game_css'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='nilpoint.location')),
                ('exit_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='nilpoint.location')),
            ],
        ),
    ]
