# Generated by Django 6.0.6 on 2026-07-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0019_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='bidirectional',
            field=models.BooleanField(default=True, help_text='Can this exit be used in reverse?'),
        ),
    ]
