# Generated by Django 6.0.6 on 2026-07-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0020_exit_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='name',
            field=models.CharField(default='Exit', help_text='A name for the exit', max_length=100),
            preserve_default=False,
        ),
    ]
