# Generated by Django 6.0.6 on 2026-07-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0021_exit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit',
            name='bidirectional',
        ),
    ]
