# Generated by Django 6.0.6 on 2026-09-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0022_remove_exit_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='np_key',
            field=models.CharField(help_text='A unique key for this location', max_length=100, null=True, unique=True),
        ),
    ]
