# Generated by Django 6.0.6 on 2026-07-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0022_remove_exit_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='default_item_graphic',
            field=models.CharField(blank=True, default=None, help_text='Static path to default item graphic. Uses nilpoint default if not set.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name of the item, will be shown to the user', max_length=100)),
                ('description', models.TextField(help_text='Description of the item')),
                ('graphic', models.CharField(blank=True, help_text='Static path for the graphic', max_length=100, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nilpoint.game')),
            ],
        ),
        migrations.CreateModel(
            name='InventroryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='nilpoint.playercharacter')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='nilpoint.item')),
            ],
        ),
        migrations.CreateModel(
            name='LocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='nilpoint.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nilpoint.location')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_items', to='nilpoint.playercharacter')),
            ],
        ),
    ]
