# Generated by Django 6.0.6 on 2026-07-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0023_game_default_item_graphic_item_inventroryitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventroryItem',
            new_name='InventoryItem',
        ),
    ]
