# Generated by Django 6.0.6 on 2026-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0024_rename_inventroryitem_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release',
            field=models.IntegerField(default=0, help_text='Current release. Ties in with the game definition so updates can be applied progressively'),
        ),
    ]
