# Generated by Django 6.0.6 on 2026-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0025_game_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='release',
            field=models.IntegerField(default=0, help_text='Current release of the game instance to which this PC is updated. Ties in with the game definition so updates can be applied progressively'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.IntegerField(default=0, help_text='Current release of the game instance. Ties in with the game definition so updates can be applied progressively'),
        ),
    ]
