# Generated by Django 6.0.6 on 2026-09-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0026_playercharacter_release_alter_game_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='asset_id',
            field=models.CharField(db_index=True, default='AAA', help_text="Developer-defined unique identifier for scripting and migrations (e.g., 'alley_front')", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exit',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='nilpoint.game'),
        ),
        migrations.AddField(
            model_name='item',
            name='asset_id',
            field=models.CharField(db_index=True, default='AAA', help_text="Developer-defined unique identifier for scripting and migrations (e.g., 'alley_front')", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='asset_id',
            field=models.CharField(db_index=True, default='AAA', help_text="Developer-defined unique identifier for scripting and migrations (e.g., 'alley_front')", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='nilpoint.game'),
        ),
        migrations.AlterField(
            model_name='location',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='nilpoint.game'),
        ),
    ]
