# Generated by Django 6.0.6 on 2026-09-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0027_exit_asset_id_exit_game_item_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='nilpoint.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='nilpoint.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='nilpoint.game'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='exit',
            constraint=models.UniqueConstraint(fields=('game', 'asset_id'), name='unique_exit_asset_per_game'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('game', 'asset_id'), name='unique_item_asset_per_game'),
        ),
    ]
