# Generated by Django 6.0.6 on 2026-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0028_alter_exit_game_alter_item_game_alter_location_game_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('game', 'asset_id'), name='unique_location_asset_per_game'),
        ),
    ]
