# Generated by Django 6.0.6 on 2026-09-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0029_location_unique_location_asset_per_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='can_drop',
            field=models.BooleanField(default=True, help_text='True if an item can be moved from a player inventory to the current location'),
        ),
        migrations.AddField(
            model_name='item',
            name='can_take',
            field=models.BooleanField(default=True, help_text='True if an item can be added to a player inventory'),
        ),
    ]
