# Generated by Django 6.0.6 on 2026-09-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nilpoint', '0030_item_can_drop_item_can_take'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('data', models.BinaryField(default=b'')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='nilpoint_it_content_b527d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_itemstate_per_object')],
            },
        ),
    ]
