# Generated by Django 6.0.6 on 2026-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0031_itemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hooks_data',
            field=models.BinaryField(default=b'', help_text="Pickled dict of interaction hooks: {'show':{}, 'handle':{}, 'can':{}}"),
        ),
    ]
