# Generated by Django 6.0.6 on 2026-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilpoint', '0031_itemstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='interaction',
            field=models.CharField(blank=True, default='', help_text="Dotted path to an InteractiveItem subclass that implements this asset's behaviour, e.g. 'cypherpunk.interactions.MysteryDevice'. Empty if the asset has no interactions.", max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='interaction_options',
            field=models.JSONField(blank=True, default=dict, help_text='Per-asset options dict, made available to the interaction class'),
        ),
    ]
