[pytest]
# Point to Django settings
DJANGO_SETTINGS_MODULE = nilpoint_harness.settings

# Force pytest to include current directory in the pythonpath
pythonpath = .

# Add default coverage flags here
# addopts = --cov=../../nilpoint_core/src/nilpoint --cov=your_local_app
